nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  youwe:
    npmAlwaysAuth: true
    npmAuthToken: "${CLOUDSMITH_YOUWE_TOKEN}"
    npmRegistryServer: "https://npm.cloudsmith.io/youwe/youwe-nodejs/"
